[package]
name = "implementation_bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.2"
anyhow = "1.0"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
